Repository NeuralEnsemble/cobrawap, pull requests merged in 2025-06, with the labels that each got.

#93 Formatting changes
  cobrawap/pipeline/stage01_data_entry/Snakefile
  cobrawap/pipeline/stage02_processing/Snakefile
  cobrawap/pipeline/stage02_processing/scripts/subsampling.py
  cobrawap/pipeline/stage03_trigger_detection/Snakefile
  cobrawap/pipeline/stage03_trigger_detection/scripts/minima.py
  cobrawap/pipeline/stage03_trigger_detection/scripts/plot_trigger_times.py
  cobrawap/pipeline/stage03_trigger_detection/scripts/remove_short_states.py
  cobrawap/pipeline/stage03_trigger_detection/scripts/threshold.py
  cobrawap/pipeline/stage04_wave_detection/Snakefile
  cobrawap/pipeline/stage04_wave_detection/scripts/critical_points.py
  cobrawap/pipeline/stage04_wave_detection/scripts/optical_flow.py
  cobrawap/pipeline/stage04_wave_detection/scripts/plot_critical_points.py
  cobrawap/pipeline/stage04_wave_detection/scripts/plot_movie_frames.py
  cobrawap/pipeline/stage04_wave_detection/scripts/trigger_clustering.py
  cobrawap/pipeline/stage04_wave_detection/scripts/wave_mode_clustering.py
  cobrawap/pipeline/stage05_channel_wave_characterization/Snakefile
  cobrawap/pipeline/stage05_channel_wave_characterization/scripts/direction_local.py
  cobrawap/pipeline/stage05_channel_wave_characterization/scripts/flow_direction_local.py
  cobrawap/pipeline/stage05_channel_wave_characterization/scripts/inter_wave_interval_local.py
  cobrawap/pipeline/stage05_channel_wave_characterization/scripts/spatial_derivative.py
  cobrawap/pipeline/stage05_wave_characterization/scripts/annotations.py
  cobrawap/pipeline/stage05_wave_characterization/scripts/direction_planar.py
  cobrawap/pipeline/stage05_wave_characterization/scripts/inter_wave_interval.py
  cobrawap/pipeline/stage05_wave_characterization/scripts/label_planar.py
  cobrawap/pipeline/stageXY_template/Snakefile
  cobrawap/pipeline/stageXY_template/scripts/script_template.py
  cobrawap/pipeline/utils/Snakefile
  cobrawap/pipeline/utils/neo_utils.py
  cobrawap/pipeline/utils/snakefile.py
Labels: formatting

#97 making doc image paths consistent & fixing join slack link
  README.rst
  cobrawap/pipeline/README.rst
Labels: documentation

#95 Fix of --version command-line argument
  cobrawap/__main__.py
Labels: bug
